# Generated by Django 3.1 on 2021-01-23 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historyapp', '0008_auto_20210123_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='powstanielistopadowe',
            name='okres',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='powstaniestyczniowe',
            name='okres',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='rewolucjaamerykanska',
            name='okres',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='powstanielistopadowe',
            name='typ',
            field=models.CharField(choices=[('bitwa', 'bitwa'), ('wydarzenie', 'wydarzenie')], default='bitwa', max_length=80),
        ),
        migrations.AlterField(
            model_name='powstaniestyczniowe',
            name='typ',
            field=models.CharField(choices=[('bitwa', 'bitwa'), ('wydarzenie', 'wydarzenie')], default='bitwa', max_length=80),
        ),
        migrations.AlterField(
            model_name='rewolucjaamerykanska',
            name='typ',
            field=models.CharField(choices=[('bitwa', 'bitwa'), ('wydarzenie', 'wydarzenie')], default='bitwa', max_length=80),
        ),
    ]
